# Generated by Django 6.0.6 on 2026-07-03 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('addr_type', models.CharField(choices=[('host', 'Host'), ('network', 'Network'), ('range', 'Range')], default='host', max_length=20)),
                ('ipv4_type', models.CharField(blank=True, choices=[('standard', 'Ip address that can be written with a subnet mask (e.g. 192.168.0.1/24)'), ('custom_range', 'IP Range')], max_length=20, null=True)),
                ('ipv6_type', models.CharField(blank=True, choices=[('standard', 'Ip address that can be written with a subnet mask (e.g. 192.168.0.1/24)'), ('custom_range', 'IP Range')], max_length=20, null=True)),
                ('ipv4Network', models.CharField(blank=True, max_length=50, null=True)),
                ('ipv6Network', models.CharField(blank=True, max_length=100, null=True)),
                ('ipv4Address_start', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv4Address_end', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6Address_start', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('ipv6Address_end', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('addr_type', models.CharField(default='Group', editable=False, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(max_length=255)),
                ('log_type', models.CharField(max_length=255)),
                ('hit_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('changed_by', models.IntegerField()),
                ('direction', models.CharField(choices=[('source', 'source'), ('destination', 'destination'), ('reverse_source', 'reverse_source'), ('reverse_destination', 'reverse_destination')], default='source', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddressGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.address')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.addressgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('VRF', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterfaceDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=3)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.interface')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
                ('policy_sequence', models.IntegerField()),
                ('enable', models.BooleanField(default=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.filter')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.interface')),
                ('interface_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.interfacedirection')),
            ],
        ),
        migrations.CreateModel(
            name='RuleFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_sequence', models.IntegerField()),
                ('enable', models.BooleanField(default=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.filter')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.rule')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(default='Group', editable=False, max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ICMPv6', 'ICMPv6'), ('GRE', 'GRE'), ('ESP', 'ESP'), ('AH', 'AH'), ('IP', 'IP')], max_length=50)),
                ('port_start', models.IntegerField(blank=True, null=True)),
                ('port_end', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(default='Service', editable=False, max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
        ),
        migrations.AddField(
            model_name='filter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
        ),
        migrations.AddField(
            model_name='addressgroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
        ),
        migrations.AddField(
            model_name='address',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
        ),
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.filter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.device')),
                ('device_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.devicegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'device_group'), name='unique_device_group_member')],
            },
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(choices=[('source', 'source'), ('destination', 'destination'), ('reverse_source', 'reverse_source'), ('reverse_destination', 'reverse_destination')], max_length=30)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='objects.rule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'match', 'object_type', 'object_id'), name='unique_rule_match_object')],
            },
        ),
        migrations.CreateModel(
            name='ServiceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.servicegroup')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'service'), name='unique_group_service')],
            },
        ),
        migrations.CreateModel(
            name='TagConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='objects.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='objects_tag_content_22546a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'content_type', 'object_id'), name='unique_tag_per_object')],
            },
        ),
        migrations.CreateModel(
            name='TenantUserMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
