# Generated by Django 6.0.6 on 2026-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tenant_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('ipv4_value', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_value', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
            ],
        ),
    ]
