# Generated by Django 6.0.6 on 2026-06-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.IntegerField()),
                ('protocol', models.CharField(max_length=50)),
                ('port_start', models.IntegerField()),
                ('port_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennant_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='ipv4_value',
        ),
        migrations.RemoveField(
            model_name='address',
            name='ipv6_value',
        ),
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
        migrations.AddField(
            model_name='address',
            name='ipv4Address_end',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='address',
            name='ipv4Address_start',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='address',
            name='ipv4Network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ipv4_type',
            field=models.CharField(blank=True, choices=[('standard', 'Ip address that can be written with a subnet mask (e.g. 192.168.0.1/24)'), ('custom_range', 'IP Range')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ipv6Address_end',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
        migrations.AddField(
            model_name='address',
            name='ipv6Address_start',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
        migrations.AddField(
            model_name='address',
            name='ipv6Network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ipv6_type',
            field=models.CharField(blank=True, choices=[('standard', 'Ip address that can be written with a subnet mask (e.g. 192.168.0.1/24)'), ('custom_range', 'IP Range')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TagObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=255)),
                ('object_id', models.IntegerField()),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tag')),
            ],
        ),
    ]
