# Generated by Django 6.0.6 on 2026-07-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_remove_rule_direction_rule_enable_rule_filter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuleFilter',
        ),
    ]
