# Generated by Django 6.0.6 on 2026-06-16 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_tenant_tenantusermember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusermember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tenantusermember',
            unique_together={('user', 'tenant')},
        ),
    ]
