# Generated by Django 6.0.6 on 2026-06-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulefilter',
            old_name='sequence',
            new_name='rule_sequence',
        ),
    ]
