# Generated by Django 6.0.6 on 2026-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_delete_rulefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icmp_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icmp_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rulematch',
            name='match',
            field=models.CharField(choices=[('source', 'source'), ('destination', 'destination'), ('reverse_source', 'reverse_source'), ('reverse_destination', 'reverse_destination'), ('any', 'any')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='addressgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'address'), name='unique_group_address'),
        ),
        migrations.AddConstraint(
            model_name='filterinterface',
            constraint=models.UniqueConstraint(fields=('interface_direction', 'filter', 'direction'), name='unique_filter_interface'),
        ),
        migrations.AddConstraint(
            model_name='interfacedirection',
            constraint=models.UniqueConstraint(fields=('interface', 'direction'), name='unique_interface_direction'),
        ),
    ]
