# Generated by Django 6.0.6 on 2026-06-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_rename_sequence_rulefilter_rule_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
                ('policy_sequence', models.IntegerField()),
                ('enable', models.BooleanField(default=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.filter')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.interface')),
            ],
        ),
    ]
