# Generated by Django 6.0.6 on 2026-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_service_icmp_code_service_icmp_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
    ]
