# Generated by Django 6.0.6 on 2026-06-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_tenantusermember_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.address')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.addressgroup')),
            ],
        ),
    ]
