# Generated by Django 6.0.6 on 2026-06-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_addressgroupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.servicegroup')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'service'), name='unique_group_service')],
            },
        ),
    ]
