# Generated by Django 6.0.6 on 2026-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_addressgroupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='port_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='port_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('icmpv6', 'ICMPv6'), ('gre', 'GRE'), ('esp', 'ESP'), ('ah', 'AH'), ('ip', 'IP')], max_length=50),
        ),
    ]
