# Generated by Django 6.0.6 on 2026-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_filterinterface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='enable',
        ),
        migrations.AddField(
            model_name='rulefilter',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='devicegroupmember',
            constraint=models.UniqueConstraint(fields=('device', 'device_group'), name='unique_device_group_member'),
        ),
    ]
