# Generated by Django 6.0.6 on 2026-07-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_remove_rule_enable_rulefilter_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.filter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
        ),
    ]
