# Generated by Django 6.0.6 on 2026-06-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_service_port_end_alter_service_port_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ICMPv6', 'ICMPv6'), ('GRE', 'GRE'), ('ESP', 'ESP'), ('AH', 'AH'), ('IP', 'IP')], max_length=50),
        ),
    ]
