# Generated by Django 6.0.6 on 2026-06-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_servicegroupmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicegroup',
            old_name='tennant_id',
            new_name='tenant_id',
        ),
    ]
