# Generated by Django 6.0.6 on 2026-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_alter_service_protocol'),
        ('objects', '0007_rename_tennant_id_servicegroup_tenant_id'),
    ]

    operations = [
    ]
