# Generated by Django 6.0.6 on 2026-06-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_merge_20260618_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addr_type',
            field=models.CharField(choices=[('host', 'Host'), ('network', 'Network'), ('range', 'Range')], default='host', max_length=20),
        ),
        migrations.AddField(
            model_name='addressgroup',
            name='addr_type',
            field=models.CharField(default='Group', editable=False, max_length=20),
        ),
    ]
