# Generated by Django 6.0.6 on 2026-06-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('objects', '0008_merge_20260618_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='objects.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='TagObject',
        ),
        migrations.AddIndex(
            model_name='tagconnection',
            index=models.Index(fields=['content_type', 'object_id'], name='objects_tag_content_22546a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagconnection',
            constraint=models.UniqueConstraint(fields=('tag', 'content_type', 'object_id'), name='unique_tag_per_object'),
        ),
    ]
