# Generated by Django 6.0.6 on 2026-06-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_address_addr_type_addressgroup_addr_type'),
        ('objects', '0009_tagconnection_delete_tagobject_and_more'),
    ]

    operations = [
    ]
