# Generated by Django 6.0.6 on 2026-06-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_merge_20260623_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(max_length=255)),
                ('log_type', models.CharField(max_length=255)),
                ('hit_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('changed_by', models.IntegerField()),
                ('enable', models.BooleanField(default=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
