# Generated by Django 6.0.6 on 2026-06-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('objects', '0011_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination'), ('reverse_source', 'Reverse Source'), ('reverse_destination', 'Reverse Destination')], max_length=30)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='objects.rule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'match', 'content_type', 'object_id'), name='unique_rule_match_object')],
            },
        ),
    ]
