# Generated by Django 6.0.6 on 2026-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_rulematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(default='Service', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='service_type',
            field=models.CharField(default='Group', editable=False, max_length=20),
        ),
    ]
