# Generated by Django 6.0.6 on 2026-06-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_rulematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.device')),
                ('device_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.devicegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'device_group'), name='unique_device_group_member')],
            },
        ),
    ]
