# Generated by Django 6.0.6 on 2026-06-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_service_service_type_servicegroup_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressgroupmember',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='addressgroupmember',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='addressgroup',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='servicegroup',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='address',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressgroup',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
            preserve_default=False,
        ),
    ]
