# Generated by Django 6.0.6 on 2026-06-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_service_service_type_servicegroup_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.IntegerField()),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='direction',
            field=models.CharField(choices=[('source', 'source'), ('destination', 'destination'), ('reverse_source', 'reverse_source'), ('reverse_destination', 'reverse_destination')], default='source', max_length=255),
        ),
        migrations.CreateModel(
            name='RuleFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('filter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.filter')),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.rule')),
            ],
        ),
    ]
