# Generated by Django 6.0.6 on 2026-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('objects', '0014_filter_rule_direction_rulefilter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulematch',
            name='unique_rule_match_object',
        ),
        migrations.RenameField(
            model_name='rulematch',
            old_name='content_type',
            new_name='object_type',
        ),
        migrations.AddConstraint(
            model_name='rulematch',
            constraint=models.UniqueConstraint(fields=('rule', 'match', 'object_type', 'object_id'), name='unique_rule_match_object'),
        ),
    ]
