# Generated by Django 6.0.6 on 2026-06-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_rename_address_id_addressgroupmember_address_and_more'),
        ('objects', '0015_remove_rulematch_unique_rule_match_object_and_more'),
    ]

    operations = [
    ]
