# Generated by Django 6.0.6 on 2026-06-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_merge_20260624_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulefilter',
            old_name='filter_id',
            new_name='filter',
        ),
        migrations.RenameField(
            model_name='rulefilter',
            old_name='rule_id',
            new_name='rule',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='filter',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objects.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rulematch',
            name='match',
            field=models.CharField(choices=[('source', 'source'), ('destination', 'destination'), ('reverse_source', 'reverse_source'), ('reverse_destination', 'reverse_destination')], max_length=30),
        ),
    ]
