# Generated by Django 6.0.6 on 2026-06-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_device_devicegroup_devicegroupmember'),
        ('objects', '0017_rename_filter_id_rulefilter_filter_and_more'),
    ]

    operations = [
    ]
