# Generated by Django 6.0.6 on 2026-06-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_merge_20260624_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='devicegroup',
            old_name='tenant_id',
            new_name='tenant',
        ),
    ]
