from aerleon.lib import naming
from aerleon import api as aerleon_api

from backend.objects.attributes.address import Address
from backend.objects.attributes.address_group import AddressGroup
from backend.objects.attributes.service import Service
from backend.objects.attributes.service_group import ServiceGroup


class PolicyRule:
    """
    A class representing a policy rule. From ER Diagram. this is basically the rule object joined with a Address, Service or group.
    Args:
    name (str): The name of the rule.
    type (str): The type of the rule, which can be "address", "service", "address_group", or "service_group".
    action (str): The action to be taken for the rule.
    object (Address | Service | AddressGroup | ServiceGroup): The object that the rule is joined with.
    direction (str, optional): The direction of the rule. Defaults to "destination".
    """
    def __init__(
        self,
        name: str,
        obj_type: str,
        action: str,
        object: Address | Service | AddressGroup | ServiceGroup,
        direction: str = "destination",
    ):
        self.name = name
        self.type = obj_type
        self.action = action
        self.object = object
        self.direction = direction
        self.members = []
        if obj_type.lower() == "address_group" and isinstance(object, AddressGroup):
            self.members = object.get_addresses()
        elif obj_type.lower() == "service_group" and isinstance(object, ServiceGroup):
            self.members = object.get_services()


class Policy:
    """
    A class for the input to aerleons Generate function.
    This class will take in a list of rules and convert them into the format that aerleon expects.
    The rules will be in the form of our internal data models (Address, Service, AddressGroup, ServiceGroup)
    and this class will convert them into the format that aerleon expects.

    Args:
        name (str): The name of the policy.
        rules (list[PolicyRule]): A list of rules in the form of our internal data models (Address, Service, AddressGroup, ServiceGroup).
        vendor (str): The name of the vendor for which to generate the configuration.
    """

    def __init__(self, name: str, rules: list[PolicyRule], vendor: str):
        self.name = name
        self.YAMLConfig = {
            "filename": name,
            "filters": {
                "header": {
                    "targets": {vendor: name},
                    "comment": f"Generated by Rulio for {vendor}",
                },
                "terms": [],
            },
        }

        self.networks = {"networks": {}}
        for rule in rules:
            match rule.type:
                case "address":
                    self.add_address(rule)
                case "service":
                    self.add_service(rule)
                case "address_group":
                    self.add_address_group(rule)
                case "service_group":
                    self.add_service_group(rule)
                case _:
                    raise ValueError(
                        f"Unsupported rule type: {rule.__class__.__name__}"
                    )

    def add_address(self, rule: PolicyRule):
        if rule.direction == "destination":
            field_name = "destination-address"
        elif rule.direction == "source":
            field_name = "source-address"
        else:
            raise ValueError(f"Unsupported rule direction: {rule.direction}")
        self.YAMLConfig["terms"].append(
            {
                "name": rule.name,
                field_name: rule.object.get_address(),
                "action": rule.action,
            }
        )

    def add_service(self, rule: PolicyRule):
        self.YAMLConfig["terms"].append(
            {
                "name": rule.name,
                "service": rule.object.get_service(),
                "action": rule.action,
            }
        )

    def add_address_group(self, rule: PolicyRule):
        if rule.direction == "destination":
            field_name = "destination-address"
        elif rule.direction == "source":
            field_name = "source-address"
        else:
            raise ValueError(f"Unsupported rule direction: {rule.direction}")
        ip_addresses = rule.members
        self.networks["networks"][rule.object.name]["values"] = ip_addresses
        self.YAMLConfig["terms"].append(
            {
                "name": rule.name,
                field_name: rule.object.name,
                "action": rule.action,
            }
        )

    def add_service_group(self, rule: PolicyRule):
        pass


def generate_config(policy: Policy) -> str:
    """
    Generates a configuration for the specified vendor based on the provided YAML configuration.

    Args:
        policy (Policy): The policy object containing the rules and configuration to be converted..

    Returns:
        str: The generated configuration as a string.
    """
    definitions = naming.Naming()
    definitions.ParseDefinitionsObject(policy.networks)
    configs = aerleon_api.Generate([policy.YAMLConfig], definitions)
    return configs
