from aerleon.lib import naming
from aerleon import api as aerleon_api


from backend.objects.attributes.address import Address
from backend.objects.attributes.address_group import AddressGroup
from backend.objects.attributes.service import Service
from backend.objects.attributes.service_group import ServiceGroup
from backend.services.get import get_service_group_members, get_address_group_members


class PolicyRule:
    """
    A class representing a policy rule. From ER Diagram. this is basically the rule object joined with a Address, Service or group.
    Args:
    name (str): The name of the rule.
    type (str): The type of the rule, which can be "address", "service", "address_group", or "service_group".
    action (str): The action to be taken for the rule.
    object (Address | Service | AddressGroup | ServiceGroup): The object that the rule is joined with.
    direction (str, optional): The direction of the rule. Defaults to "destination".
    """

    def __init__(
        self,
        name: str,
        obj_type: str,
        action: str,
        object: Address | Service | AddressGroup | ServiceGroup,
        sequence: int = 0,
        direction: str = "destination",
    ):
        self.name = name
        self.type = obj_type
        self.action = action
        self.object = object
        self.direction = direction
        self.sequence = sequence
        self.members = []
        self.object_name = object.name
        if obj_type.lower() == "address" and isinstance(object, Address):
            self.members = object.get_address()
        elif obj_type.lower() == "service" and isinstance(object, Service):
            self.members = object
        elif obj_type.lower() == "address_group" and isinstance(object, AddressGroup):
            self.members = get_address_group_members(request=None, address_group_id=object.id)
        elif obj_type.lower() == "service_group" and isinstance(object, ServiceGroup):
            self.members = get_service_group_members(request=None, service_group_id=object.id)


class Policy:
    """
    A class for the input to aerleons Generate function.
    This class will take in a list of rules and convert them into the format that aerleon expects.
    The rules will be in the form of our internal data models (Address, Service, AddressGroup, ServiceGroup)
    and this class will convert them into the format that aerleon expects.

    Args:
        name (str): The name of the policy.
        rules (list[PolicyRule]): A list of rules in the form of our internal data models (Address, Service, AddressGroup, ServiceGroup).
        vendor (str): The name of the vendor for which to generate the configuration.
    """

    def __init__(self, name: str, rules: list[PolicyRule], vendor: str, policy_type: str = "extended"):
        self.name = name
        if vendor.lower() == "paloalto":
            self.YAMLConfig = {
                "filename": name,
                "filters": [
                    {
                        "header": {
                            "targets": {vendor: policy_type},
                        },
                        "terms": [],
                    },
                ],
            }
        else:
            self.YAMLConfig = {
                "filename": name,
                "filters": [
                    {
                        "header": {
                            "targets": {vendor: f"{name} {policy_type}"},
                            "comment": f"Generated by Rulio for {vendor}",
                        },
                        "terms": [],
                    },
                ],
            }
        rules.sort(key=lambda r: r.sequence)

        self.networks = {"networks": {}}
        self.services = {"services": {}}
        for rule in rules:
            match rule.type:
                case "address":
                    self.add_address(rule)
                case "service":
                    self.add_service(rule)
                case "address_group":
                    self.add_address_group(rule)
                case "service_group":
                    self.add_service_group(rule)
                case _:
                    raise ValueError(f"Unsupported rule type: {rule.__class__.__name__}")

    def add_address(self, rule: PolicyRule):
        if rule.direction == "destination":
            field_name = "destination-address"
        elif rule.direction == "source":
            field_name = "source-address"
        else:
            raise ValueError(f"Unsupported rule direction: {rule.direction}")

        self.YAMLConfig["filters"][0]["terms"].append(
            {
                "name": rule.name,
                field_name: rule.object_name,
                "action": rule.action,
            }
        )
        values = []
        for ipv in rule.members:
            for addr in ipv:
                values.append(str(addr))
        self.networks["networks"][rule.object_name] = {"values": values}

    def add_service(self, rule: PolicyRule):
        if rule.direction == "destination":
            field_name = "destination-port"
        elif rule.direction == "source":
            field_name = "source-port"
        else:
            raise ValueError(f"Unsupported rule direction: {rule.direction}")

        service = rule.members
        service_name = service.name
        has_ports = service.is_port_based()
        port_value = service.get_ports()

        entry = {"protocol": service.get_protocol()}
        if port_value is not None:
            entry["port"] = port_value

        self.services["services"][service_name] = [entry]

        term = {
            "name": rule.name,
            "action": rule.action,
            "protocol": service.get_protocol(),
        }

        if has_ports:
            term[field_name] = service_name

        self.YAMLConfig["filters"][0]["terms"].append(term)

    def add_address_group(self, rule: PolicyRule):
        if rule.direction == "destination":
            field_name = "destination-address"
        elif rule.direction == "source":
            field_name = "source-address"
        else:
            raise ValueError(f"Unsupported rule direction: {rule.direction}")

        values = []

        for address in rule.members:
            ipv4_addrs, ipv6_addrs = address.get_address()

            for addr in ipv4_addrs:
                values.append(str(addr))

            for addr in ipv6_addrs:
                values.append(str(addr))

        self.networks["networks"][rule.object_name] = {"values": values}

        self.YAMLConfig["filters"][0]["terms"].append(
            {
                "name": rule.name,
                field_name: rule.object_name,
                "action": rule.action,
            }
        )

    def add_service_group(self, rule: PolicyRule):
        if rule.direction == "destination":
            field_name = "destination-port"
        elif rule.direction == "source":
            field_name = "source-port"
        else:
            raise ValueError(f"Unsupported rule direction: {rule.direction}")

        for i, service in enumerate(rule.members):
            service_name = service.name
            has_ports = service.is_port_based()
            port_value = service.get_ports()

            entry = {"protocol": service.get_protocol()}
            if port_value is not None:
                entry["port"] = port_value

            self.services["services"][service_name] = [entry]

            term = {
                "name": f"{rule.name}_Rule_{i}",
                "action": rule.action,
                "protocol": service.get_protocol(),
            }

            if has_ports:
                term[field_name] = service_name

            self.YAMLConfig["filters"][0]["terms"].append(term)


def generate_config(policy: Policy) -> str:
    """
    Generates a configuration for the specified vendor based on the provided YAML configuration.

    Args:
        policy (Policy): The policy object containing the rules and configuration to be converted..

    Returns:
        str: The generated configuration as a string.
    """
    definitions = naming.Naming()

    definitions_obj = {
        "networks": policy.networks.get("networks", {}),
        "services": policy.services.get("services", {}),
    }

    definitions.ParseDefinitionsObject(definitions_obj, policy.name)

    configs = aerleon_api.Generate([policy.YAMLConfig], definitions)
    return configs
