import pytest
import yaml

from backend.services.attribute_objects.create_attribute_objects import create_service
from backend.services.config_generation.build import build_policies_for_interface, build_policy_from_filter
from backend.services.config_generation.generate_config import (
    generate_config,
    generate_multi_policy_config,
    merge_policies,
)
from backend.services.filter_objects.create_filter_objects import create_filter, create_rule
from backend.services.membership import add_filter_to_interface, add_objects_to_rule
from backend.services.tenant_objects.create_tenant_objects import create_device, create_interface
from backend.services.update import update_rule
from backend.utils.logger import set_up_logger
from backend.utils.write_to_file import write_configuration_to_file
from constants import TEST_LOGPATH


logger = set_up_logger(__name__)


@pytest.mark.django_db
class TestBuildPolicyFromObjects:
    def test_build_policy_from_simple_filter_object(self, request_with_session, sample_addresses):
        filter_obj = create_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Simple_Build_Filter",
            description="Simple build test filter",
        )
        rule = create_rule(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Simple_Build_Rule",
            filter=filter_obj,
            rule_sequence=1,
            enable=True,
            description="Simple build test rule",
            action="accept",
            log_type="all",
            hit_count=0,
        )

        response = add_objects_to_rule(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            rule_id=rule.id,
            match_type="source",
            objects=[sample_addresses[0]],
        )
        if response["error_count"] > 0:
            logger.error(f"Error adding objects to rule: {response['errors']}")
        assert response["error_count"] == 0
        assert response["added_count"] > 0

        policy = build_policy_from_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            filter_id=filter_obj.id,
            policy_sequence=10,
            vendor="juniper",
            target_spec=None,
        )
        assert policy is not None

        assert policy.name == filter_obj.name.replace(" ", "_")
        assert policy.vendor == "juniper"
        assert policy.target_spec is None
        assert policy.policy_sequence == 10
        assert policy.warnings == []

        yaml_config = policy.YAMLConfig
        assert yaml_config["filename"] == filter_obj.name.replace(" ", "_")
        assert len(yaml_config["filters"]) == 1

        filter_config = yaml_config["filters"][0]
        assert filter_config["header"]["targets"] == {"juniper": filter_obj.name.replace(" ", "_")}
        assert filter_config["header"]["comment"] == "Generated by Rulio for juniper"

        terms = filter_config["terms"]
        assert len(terms) == 1

        term = terms[0]
        assert term["name"] == rule.name.replace(" ", "_")[:62]
        assert term["action"] == rule.action
        assert term["source-address"] == [sample_addresses[0].name]
        assert "protocol" not in term
        assert "destination-port" not in term

        assert sample_addresses[0].name in policy.networks["networks"]
        assert policy.networks["networks"][sample_addresses[0].name]["values"] == ["192.168.1.0/24"]
        assert policy.services["services"] == {}

        config = generate_config(policy)
        filepath = TEST_LOGPATH / "build_from_filter" / "JUNIPER_simple_built_policy.yaml"
        filedir = TEST_LOGPATH / "build_from_filter"
        write_configuration_to_file(
            config,
            filepath,
            filedir,
            "juniper",
            __name__,
            generated_by="build_test",
            log_for_vendors=["juniper"],
        )

    def test_build_policy_from_complex_filter_object(
        self,
        sample_filters,
        sample_rules,
        request_with_session,
        realistic_acl_addresses,
        realistic_acl_services,
        realistic_acl_address_groups,
        realistic_acl_service_groups,
    ):
        filter_id = sample_filters[1].id
        rules = [
            sample_rules[0].id,
            sample_rules[1].id,
            sample_rules[2].id,
            sample_rules[3].id,
        ]

        for i, rule_id in enumerate(rules):
            update_rule(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                rule_id=rule_id,
                filter=sample_filters[1],
                rule_sequence=i + 1,
            )

        responses = [
            add_objects_to_rule(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                rule_id=rules[0],
                match_type="source",
                objects=realistic_acl_addresses,
            ),
            add_objects_to_rule(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                rule_id=rules[1],
                match_type="destination",
                objects=realistic_acl_services,
            ),
            add_objects_to_rule(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                rule_id=rules[2],
                match_type="source",
                objects=realistic_acl_address_groups,
            ),
            add_objects_to_rule(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                rule_id=rules[3],
                match_type="destination",
                objects=realistic_acl_service_groups,
            ),
        ]
        assert all(response["error_count"] == 0 for response in responses)

        policy = build_policy_from_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            filter_id=filter_id,
            policy_sequence=10,
            vendor="juniper",
            target_spec=None,
        )
        assert policy is not None

        yaml_config = policy.YAMLConfig
        assert yaml_config["filename"] == sample_filters[1].name.replace(" ", "_")
        assert len(yaml_config["filters"]) == 1

        filter_config = yaml_config["filters"][0]
        assert filter_config["header"]["targets"] == {"juniper": sample_filters[1].name.replace(" ", "_")}
        assert filter_config["header"]["comment"] == "Generated by Rulio for juniper"

        terms = filter_config["terms"]
        assert len(terms) == 7

        assert policy.name == sample_filters[1].name.replace(" ", "_")
        assert policy.vendor == "juniper"
        assert policy.policy_sequence == 10

        # Rule 1: source addresses only
        rule_1_name = sample_rules[0].name.replace(" ", "_")[:62]
        rule_1_terms = [term for term in terms if term["name"] == rule_1_name]
        assert len(rule_1_terms) == 1

        rule_1_term = rule_1_terms[0]
        assert rule_1_term["action"] == sample_rules[0].action
        assert rule_1_term["source-address"] == [address.name for address in realistic_acl_addresses]
        assert "protocol" not in rule_1_term

        # Rule 2: destination services only -> split by protocol
        rule_2_base = sample_rules[1].name.replace(" ", "_")[:62]
        rule_2_terms = [term for term in terms if term["name"].startswith(rule_2_base)]
        assert len(rule_2_terms) == 3

        rule_2_protocols = {term["protocol"] for term in rule_2_terms}
        assert rule_2_protocols == {"tcp", "udp", "icmp"}

        rule_2_tcp = next(term for term in rule_2_terms if term["protocol"] == "tcp")
        rule_2_udp = next(term for term in rule_2_terms if term["protocol"] == "udp")
        rule_2_icmp = next(term for term in rule_2_terms if term["protocol"] == "icmp")

        assert rule_2_tcp["destination-port"] == ["ACL_HTTP", "ACL_HTTPS", "ACL_DNS_TCP"]
        assert rule_2_udp["destination-port"] == ["ACL_DNS_UDP"]
        assert "destination-port" not in rule_2_icmp

        # Rule 3: source address groups only
        rule_3_name = sample_rules[2].name.replace(" ", "_")[:62]
        rule_3_terms = [term for term in terms if term["name"] == rule_3_name]
        assert len(rule_3_terms) == 1

        rule_3_term = rule_3_terms[0]
        assert rule_3_term["action"] == sample_rules[2].action
        assert rule_3_term["source-address"] == [group.name for group in realistic_acl_address_groups]
        assert "protocol" not in rule_3_term

        # Rule 4: destination service groups only -> split by protocol
        rule_4_base = sample_rules[3].name.replace(" ", "_")[:62]
        rule_4_terms = [term for term in terms if term["name"].startswith(rule_4_base)]
        assert len(rule_4_terms) == 2

        rule_4_protocols = {term["protocol"] for term in rule_4_terms}
        assert rule_4_protocols == {"tcp", "udp"}

        rule_4_tcp = next(term for term in rule_4_terms if term["protocol"] == "tcp")
        rule_4_udp = next(term for term in rule_4_terms if term["protocol"] == "udp")

        assert rule_4_tcp["destination-port"] == ["ACL_HTTP", "ACL_HTTPS", "ACL_DNS_TCP"]
        assert rule_4_udp["destination-port"] == ["ACL_DNS_UDP"]

        assert len(policy.warnings) == 2
        assert all("was split into multiple terms" in warning for warning in policy.warnings)

        for address in realistic_acl_addresses:
            assert address.name in policy.networks["networks"]
        for group in realistic_acl_address_groups:
            assert group.name in policy.networks["networks"]

        for service in realistic_acl_services:
            assert service.name in policy.services["services"]

        config = generate_config(policy)
        filepath = TEST_LOGPATH / "build_from_filter" / "JUNIPER_complex_built_policy.yaml"
        filedir = TEST_LOGPATH / "build_from_filter"
        write_configuration_to_file(
            config,
            filepath,
            filedir,
            "juniper",
            __name__,
            generated_by="build_test",
            log_for_vendors=["juniper"],
        )

    def test_protocol_term_split(
        self,
        request_with_session,
        sample_rules,
    ):
        split_filter = create_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Protocol_Split_Filter",
            description="Filter to test protocol term splitting",
        )
        split_rule = create_rule(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Protocol_Split_Rule",
            filter=split_filter,
            rule_sequence=1,
            enable=True,
            description="This term should be split into multiple terms based on protocol",
            action="accept",
            log_type="all",
            hit_count=0,
        )

        # Add a service that has multiple protocols (e.g., TCP and UDP)
        service_tcp_80 = create_service(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Test_Service_TCP",
            description="Test service with TCP protocol",
            protocol="tcp",
            port_start=80,
            port_end=80,
        )
        service_udp_53 = create_service(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Test_Service_UDP",
            description="Test service with UDP protocol",
            protocol="udp",
            port_start=53,
            port_end=53,
        )

        icmp_service = create_service(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Test_Service_ICMP",
            description="Test service with ICMP protocol",
            protocol="icmp",
        )

        add_objects_to_rule(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            rule_id=split_rule.id,
            match_type="destination",
            objects=[service_tcp_80, service_udp_53, icmp_service],
        )
        single_term_filter = create_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Single_Term_Filter",
            description="Filter to test single term",
        )

        single_term_rule = create_rule(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Single_Term_Rule",
            filter=single_term_filter,
            rule_sequence=1,
            enable=True,
            description="This term should remain as a single term",
            action="accept",
            log_type="all",
            hit_count=0,
        )
        service_udp_80 = create_service(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Test_Service_UDP_80",
            description="Test service with UDP protocol on port 80",
            protocol="udp",
            port_start=80,
            port_end=80,
        )
        add_objects_to_rule(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            rule_id=single_term_rule.id,
            match_type="destination",
            objects=[service_udp_80, service_tcp_80],
        )

        policy_split_term = build_policy_from_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            filter_id=split_filter.id,
            policy_sequence=10,
            vendor="juniper",
            target_spec=None,
        )

        policy_single_term = build_policy_from_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            filter_id=single_term_filter.id,
            policy_sequence=20,
            vendor="juniper",
            target_spec=None,
        )

        # Check that the split term policy has multiple terms for the same rule
        split_terms = policy_split_term.YAMLConfig["filters"][0]["terms"]
        assert len(split_terms) == 3  # Should be split into TCP, UDP, and ICMP terms
        protocols_split = {term["protocol"] for term in split_terms}
        assert protocols_split == {"tcp", "udp", "icmp"}

        # Check that the single term policy has only one term for the rule
        single_terms = policy_single_term.YAMLConfig["filters"][0]["terms"]
        assert len(single_terms) == 1  # Should remain as a single term
        assert single_terms[0]["protocol"] == ["udp", "tcp"] or single_terms[0]["protocol"] == [
            "tcp",
            "udp",
        ]  # Should include both protocols in one term

        config_split = generate_config(policy_split_term)
        config_single = generate_config(policy_single_term)
        write_configuration_to_file(
            config_split,
            TEST_LOGPATH / "build_from_filter" / "JUNIPER_split_term_policy.yaml",
            TEST_LOGPATH / "build_from_filter",
            "juniper",
            __name__,
            generated_by="build_test",
            log_for_vendors=["juniper"],
        )
        write_configuration_to_file(
            config_single,
            TEST_LOGPATH / "build_from_filter" / "JUNIPER_single_term_policy.yaml",
            TEST_LOGPATH / "build_from_filter",
            "juniper",
            __name__,
            generated_by="build_test",
            log_for_vendors=["juniper"],
        )

    def test_build_policies_for_interface_and_merge(
        self,
        request_with_session,
        sample_rules_with_objects,
        sample_filters,
    ):
        new_filter = create_filter(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            name="Test Filter for Interface",
            description="This is a test filter for interface",
        )
        update_rule(
            actor=request_with_session.user,
            tenant_id=request_with_session.tenant_id,
            rule_id=sample_rules_with_objects[1].id,
            filter=new_filter,
            rule_sequence=1,
        )

        for vendor in ["juniper", "cisco"]:
            device = create_device(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                name=f"{vendor.upper()}_Test_Device",
                description="This is a test device",
                platform=vendor,
                type="firewall",
            )
            interface = create_interface(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                name=f"{vendor.upper()}_Test_Interface",
                description="This is a test interface",
                type="ethernet",
                device_id=device.id,
                VRF=None,
            )

            add_filter_to_interface(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                interface_id=interface.id,
                filter_id=new_filter.id,
                policy_sequence=5,
                enable=False,
                direction="in",
            )
            add_filter_to_interface(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                interface_id=interface.id,
                filter_id=sample_filters[0].id,
                policy_sequence=10,
                enable=True,
                direction="in",
            )
            add_filter_to_interface(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                interface_id=interface.id,
                filter_id=sample_filters[1].id,
                policy_sequence=20,
                enable=True,
                direction="in",
            )

            policies = build_policies_for_interface(
                actor=request_with_session.user,
                tenant_id=request_with_session.tenant_id,
                interface_id=interface.id,
                target_spec=None,
                direction="in",
            )

            assert len(policies) == 2
            assert policies[0].policy_sequence == 10
            assert policies[1].policy_sequence == 20

            policy_1 = policies[0]
            policy_2 = policies[1]

            assert policy_1.vendor == vendor
            assert policy_2.vendor == vendor

            yaml_1 = policy_1.YAMLConfig
            yaml_2 = policy_2.YAMLConfig

            assert yaml_1["filters"][0]["header"]["targets"] == {vendor: policy_1.name}
            assert yaml_2["filters"][0]["header"]["targets"] == {vendor: policy_2.name}

            terms_1 = yaml_1["filters"][0]["terms"]
            terms_2 = yaml_2["filters"][0]["terms"]

            assert len(terms_1) == 1
            assert len(terms_2) == 2

            assert terms_1[0]["name"] == sample_rules_with_objects[0].name.replace(" ", "_")[:62]
            assert terms_1[0]["action"] == sample_rules_with_objects[0].action
            assert terms_1[0]["source-address"] == ["Test_Address_1"]

            assert terms_2[0]["name"] == sample_rules_with_objects[2].name.replace(" ", "_")[:62]
            assert terms_2[0]["action"] == sample_rules_with_objects[2].action
            assert terms_2[0]["source-address"] == ["Test_Address_2"]

            assert terms_2[1]["name"] == sample_rules_with_objects[3].name.replace(" ", "_")[:62]
            assert terms_2[1]["action"] == sample_rules_with_objects[3].action
            assert terms_2[1]["protocol"] == "udp"
            assert terms_2[1]["destination-port"] == ["Test_Service2"]

            merged_policy = merge_policies(policies, name=None)
            assert merged_policy is not None
            assert len(merged_policy.YAMLConfig["filters"]) == 2

            logger.info(
                "Generated merged policy YAML:\n%s",
                yaml.dump(merged_policy.YAMLConfig, sort_keys=False, default_flow_style=False),
            )

            config = generate_multi_policy_config(policies)
            assert config is not None
            assert hasattr(config, "keys")
            assert len(config.keys()) >= 1

            filepath = TEST_LOGPATH / "build_interface" / f"{interface.name}_built_policy.yaml"
            filedir = TEST_LOGPATH / "build_interface"
            write_configuration_to_file(
                config,
                filepath,
                filedir,
                device.platform,
                __name__,
                generated_by="build_test",
                log_for_vendors=["juniper", "cisco"],
            )
