from backend.services.generate_config import generate_config, PolicyRule, Policy
from backend.objects.attributes.address import Address
from backend.utils.logger import set_up_logger


logger = set_up_logger(__name__)


class TestGenerateConfig:

    def test_generate_config(self):


        vendor = "cisco"

        destination_address1 = Address(
            name="Test Address 1",
            description="This is a test address",
            tenant_id=42,
            ipv4_type="standard",
            ipv6_type=None,
            ipv4Network="192.168.1.0/24",
            ipv6Network=None,
            ipv4Address_start=None,
            ipv4Address_end=None,
            ipv6Address_start=None,
            ipv6Address_end=None,
        )

        destination_address2 = Address(
            name="Test Address 2",
            description="This is another test address",
            tenant_id=42,
            ipv4_type="standard",
            ipv6_type=None,
            ipv4Network="0.0.0.0/0",
            ipv6Network=None,
            ipv4Address_start=None,
            ipv4Address_end=None,
            ipv6Address_start=None,
            ipv6Address_end=None,
        )

        PolicyRule1 = PolicyRule(
            name="Test Rule 1",
            obj_type="address",
            action="allow",
            object=destination_address1,
            direction="destination"
        )

        PolicyRule2 = PolicyRule(
            name="Test Rule 2",
            obj_type="address",
            action="deny",
            object=destination_address2,
            direction="destination"
        )

        policy = Policy(name="Test Policy", rules=[PolicyRule1, PolicyRule2], vendor=vendor)

        logger.info(f"Generated policy: {policy.YAMLConfig}")

        assert policy is not None
        assert policy.name == "Test Policy"
        assert policy.YAMLConfig is not None
        assert policy.YAMLConfig["filename"] == "Test Policy"
        assert policy.YAMLConfig["filters"]["header"]["targets"] == {"cisco": "Test Policy"}
        assert policy.YAMLConfig["filters"]["header"]["comment"] == "Generated by Rulio for cisco"
        assert len(policy.YAMLConfig["filters"]["terms"]) == 2
        assert policy.YAMLConfig["filters"]["terms"][0]["name"] == "Test Rule 1"
        assert policy.YAMLConfig["filters"]["terms"][0]["destination-address"] == "192.168.1.0/24"
        assert policy.YAMLConfig["filters"]["terms"][0]["action"] == "allow"
        assert policy.YAMLConfig["filters"]["terms"][1]["name"] == "Test Rule 2"
        assert policy.YAMLConfig["filters"]["terms"][1]["destination-address"] == "0.0.0.0/0"
        assert policy.YAMLConfig["filters"]["terms"][1]["action"] == "deny"

        config = generate_config(policy)
       

        logger.info(f"Generated config:\n{config}")
