# .github/workflows/tests.yml
name: Run pytest with Docker Compose

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Build and start containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for startup
        run: sleep 10

      - name: Run tests
        run: docker compose -f docker-compose.yml exec -T web pytest

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.yml down -v